name: Deploy

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPOSITORY_NAME: ${{ secrets.DOCKER_REPOSITORY }}

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Login into Docker
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Current Time
        id: datum
        run: echo "date=$(date +'%Y-%m-%d--%M-%S')" >> "$GITHUB_ENV"
      
      - name: Create Docker picture
        run: |
          echo ${{ steps.datum.outputs.date }}
          echo "docker build . --file Dockerfile --tag $DOCKER_USERNAME/$REPONAME:$date"
          docker build . --file Dockerfile --tag $DOCKER_USERNAME/$REPONAME:$date

      - name: Push Docker Picture
        run: |
          docker push $DOCKER_USERNAME/$REPONAME:$date
