name: Deploy

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Login into Docker
        run: echo "${DOCKER_PASSWORD}" | sudo docker login -u "${DOCKER_USERNAME}" --password-stdin
      
      - name: Current Time
        id: datum
        run: echo "date=$(date +'%Y-%m-%d--%H-%M-%S')" >> "$GITHUB_ENV"
      
      - name: Create Docker picture
        run: |
          echo ${{ steps.datum.outputs.date }}
          sudo echo "docker build . --file Dockerfile --tag $DOCKER_USERNAME/$REPONAME:$date"
      
      - name: Push Docker Picture
        run: |
          sudo docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:${{ steps.datum.outputs.date }}
